### ISSUE TITLE
Add support for rmvb/rm video file format

### ISSUE THREAD

**Issue by inits** [gabriel-vasile/mimetype#100]
1) Specify the MIME type and extension for which to add support
the video file rmvb and rm 
2) Share an example file
...
3) Optionally, add a reference to the specification of the file format.
...

**Comment by gabriel-vasile** [comment]
Commit eecce1107f9b1b2acf65df4e00ed94d31809a03c has the new code. If you need it, I can make a new release tag out of it.

**Comment by inits** [comment]
thanks
