### ISSUE TITLE
Return just the mimetype without charset

### ISSUE THREAD

**Issue by discobean** [gabriel-vasile/mimetype#101]
Hi,

The documentation suggests that `text/plain` or similar is returned by the `String()` method, but I got `text/plain; charset=utf-8` when parsing some bytes with plaintext.

Is there a way to return just the charset, or just the mimetype?

**Comment by gabriel-vasile** [comment]
Hi,
[ParseMediaType](https://godoc.org/mime#ParseMediaType) function from the standard library can be used to break a MIME type into `type/subtype` and a map of the optional parameters.

**Comment by discobean** [comment]
Thank you, I wasn't aware of it - Great library btw, thanks for your efforts.
