### ISSUE TITLE
Add support for GIMP ggr, gpl, xcf, pat, gbr and gih file formats

### ISSUE THREAD

**Issue by gabriel-vasile** [gabriel-vasile/mimetype#102]
1) Specify the MIME type and extension for which to add support
text/x-gimp-ggr, .ggr
text/x-gimp-gpl .gpl
image/x-xcf .xcf
image/x-gimp-pat .pat
image/x-gimp-gbr .gbr
image/x-gimp-gih .gih

2) Share an example file
Can be generated with GIMP.
3) Optionally, add a reference to the specification of the file format.
https://github.com/file/file/blob/master/magic/Magdir/gimp

**Comment by EclesioMeloJunior** [comment]
Ok, I'm working on extension .grr -> MIME text/x-gimp-ggr

**Comment by gabriel-vasile** [comment]
#128 solved XCF, PAT and GBR.
