### ISSUE TITLE
Add support for getting MIME from extension

### ISSUE THREAD

**Issue by abdullah2993** [gabriel-vasile/mimetype#107]
Add a helper function for getting `MIME` from extension [similar to this](https://golang.org/pkg/mime/#TypeByExtension)

**Comment by gabriel-vasile** [comment]
Hi @abdullah2993! 
I'm not really sure what is the benefit of adding that function instead of just using the alternative you linked. Could you please provide some details on why this is needed, or add a use case.

**Comment by gabriel-vasile** [comment]
Closing. Please use [mime.TypeByExtension](https://golang.org/pkg/mime/#TypeByExtension).
