### ISSUE TITLE
DetectReader always text/plain; charset=utf-8

### ISSUE THREAD

**Issue by clong1995** [gabriel-vasile/mimetype#108]
file:"d771f1704e142f84dde1fa59dd8ef6a6.pdf"
`
mime,_ := mimetype.DetectReader(finalFile) //text/plain; charset=utf-8
mime, _ := mimetype.DetectFile("xxx/xxx/d771f1704e142f84dde1fa59dd8ef6a6.pdf")//application/pdf
`

**Comment by gabriel-vasile** [comment]
Most likely, your code is reading all the data from `finalFile` before `mimetype` is called:
If that is the case, you will have to move the file offset to the start of the file with `Seek`:
```go
_, err := finalFile.Seek(0, io.SeekStart)
mime, err := mimetype.DetectReader(finalFile)
```
