### ISSUE TITLE
Outlook mails are detected as powerpoint files

### ISSUE THREAD

**Issue by Fank** [gabriel-vasile/mimetype#109]
**Attach the file for which the detection is inaccurate**
[asd.zip](https://github.com/gabriel-vasile/mimetype/files/4932104/asd.zip)

**Expected mime type**
application/vnd.ms-outlook

**Returned mime type**
application/vnd.ms-powerpoint

**Version of the library you are using**
e1ee525cf8c84a3b11ea5aceb480e9414a51516c

**Output of `go version`**
go version go1.14.4 linux/amd64

**Additional context**
Microsoft mimetypes:
https://docs.microsoft.com/en-us/microsoft-365/compliance/supported-filetypes-datainvestigations?view=o365-worldwide

**Comment by gabriel-vasile** [comment]
Hi, please run 
```bash
go get github.com/gabriel-vasile/mimetype@ole-clsid
```
and confirm it is fixed. I will make a release out of it if everything works.

**Comment by Fank** [comment]
LGTM :+1:
