### ISSUE TITLE
Add support for semicolon separated file format

### ISSUE THREAD

**Issue by MorpheusXAUT** [gabriel-vasile/mimetype#112]
1) Specify the MIME type and extension for which to add support
No official MIME type available, potentially as an "extension" to `text/csv`. File extension nearly always `.csv`

2) Share an example file
```
# some comments;;;;;;;;;;;;;;;;
Start Date ;Start Time;End Date;End Time;Event Title ;All Day Event;No End Time;Event Description;Contact ;Contact Email;Contact Phone;Location;Category;Mandatory;Registration;Maximum;Last Date To Register
# hello;;;;;;;;;;;;;;;;
09/05/2011;3:00:00 PM;09/05/2011;;Social Studies Dept. Meeting;N;Y;Department meeting;Chris Gallagher;cgallagher@schoolwires.com;814-555-5179;High School;2;N;N;25;09/02/2011
# see ya;;;;;;;;;;;;;;;;
09/05/2011;6:00:00 PM;09/05/2011;8:00:00 PM;Curriculum Meeting;N;N;Curriculum Meeting;Chris Gallagher;cgallagher@schoolwires.com;814-555-5179;High School;2;N;N;25;09/02/2011
```

3) Optionally, add a reference to the specification of the file format.
Whilst a semicolon separated file is not _strictly_ in accordance with the definition of the CSV format/MIME type from [RFC 4180](https://tools.ietf.org/html/rfc4180#section-2) and does not appear to have an official MIME type assigned, it seems somewhat common (at least in Europe) to have `.csv` files using semicolons as delimiters, especially since Excel/other spreadsheet software have it as one of the default options when exporting to "CSV".

Similar to the existing `Csv` and `Tsv` matchers, an additional one for semicolons (`Ssv`? 🤔 ) would be highly appreciated.

Happy to put in a quick PR if that'd help.

**Comment by brunnre8** [comment]
The semicolon isn't a default of Excel, it's a default of the regional settings of windows itself.  
You can overwrite this within the regional settings --> advanced --> list separator or something like that.

Excel just uses the system separator then.

**Comment by gabriel-vasile** [comment]
Same as https://github.com/gabriel-vasile/mimetype/issues/156#issuecomment-853862718.
