### ISSUE TITLE
DetectFile detect json as plain text

### ISSUE THREAD

**Issue by hdhog** [gabriel-vasile/mimetype#12]
test file
```
{
	"AllowIP": [
		"127.0.0.1"
	],
	"AllowRawReadingFromPath": [
		"c:/j(/|/.*)?$",
		"./.*"
	],
	"ArgsLoggingExclude": [],
	"Binding": "0.0.0.0:53638",
	"DebugLevel": "debug",
	"DebugLevel1": "error",
	"EnableAuthentication": true,
	"EnableIPAcl": false,
	"LogMaxAge": 10,
	"LogMaxBackups": 3,
	"LogMaxSize": 5,
	"RawReadingFilesEnabled": false,
	"RawReadingMaxKbytes": 4096,
	"SQL": {
		"BackupCount": 5,
		"BackupDir": "backups",
		"BackupPeriod": 1,
		"Queries": [
			{
				"Name": "migrations",
				"Query": "SELECT * FROM ALALA;"
			}
		]
	},
	"SvcDescription": "testing environment",
	"SvcDisplayName": "testing",
	"SvcNameSuffix": "",
	"TemplateData": {},
	"WorkerPool": {
		"Max": 5,
		"Timeout": 5
	}
}
```

test code
```
package main

import (
	"fmt"
	"io/ioutil"

	"github.com/gabriel-vasile/mimetype"
)

func main() {

	data, _ := ioutil.ReadFile("test.json")
	fmt.Println(mimetype.Detect(data))
	fmt.Println(mimetype.DetectFile("test.json"))
}
```

Result 
```
application/json json
text/plain txt <nil>
```

**Comment by WheeskyJack** [comment]
It seems upper limit of 520 bytes in DetectReader() function is causing this error.
The json identifying function "matchers.Json()" requires complete file data instead of first 520 bytes; this causes the detection to fail and hence its parent is identified as valid mimetype which is "text/plain" in this case.

**Comment by WheeskyJack** [comment]
@gabriel-vasile , i would like to work on this issue if no one is working on it.

**Comment by gabriel-vasile** [comment]
Sure. Did you come up with any approach to this problem?

**Comment by WheeskyJack** [comment]
Hi,
I am thinking this might be recurring problem and not just specific to json type. New types may get added which may not have magic numbers associated with them explicitly. 
So , what if we make provision to specifically add exceptions for such types (until more performance oriented solution is found for each of such types)? This way functionality which package supports will not be hampered(only specific type's performance will get a hit) and user will be easily able to extend the desired types which has no magic numbers as such.

Also,
I went through go json package implementation of the validity function and found it also requires complete json for validation(as it is matching opening and closing braces etc.). 
I thought of using regexp for matching json; but this approach also need complete data.
Besides that, even current implementation has its own flaw. What if my regular text file accidentally matches the json criteria?  

So, I think we are having two problems at hand now. 
1. detect json from first 520 bytes
2. And if not able to do, what will be next step of actions to still support this and other such types.

Please share your thoughts...
Regards.

**Comment by WheeskyJack** [comment]
@gabriel-vasile have raised PR with above design.
