### ISSUE TITLE
Incorrect recognition of pptx with the current ReadLimit.

### ISSUE THREAD

**Issue by MK5555** [gabriel-vasile/mimetype#120]
I tested library using 64 presentation but  5/64 presentations were detected as zip archive. After increasing ReadLimit (i set 30720 instead 3720), all presentations were detected as pptx.  I would like to know which ReadLimit is optimal for defining extensions?

**Comment by gabriel-vasile** [comment]
For pptx and other microsoft office files, the signature can be placed anywhere in the file and some programs place it at the end of the file. Increasing ReadLimit does provider better detection, but it also means more memory is used.
I'm thinking about adding a function to let users set the ReadLimit:
```go
// Read n bytes from input when detecting.
// If n is zero, read whole file.
func SetReadLimit(n uint)
```
