### ISSUE TITLE
Add support for Adobe FDF file format

### ISSUE THREAD

**Issue by gabriel-vasile** [gabriel-vasile/mimetype#124]
1) Specify the MIME type and extension for which to add support
application/vnd.fdf, .fdf

2) Share an example file
...
3) Optionally, add a reference to the specification of the file format.
http://en.wikipedia.org/wiki/Forms_Data_Format

**Comment by felipecaputo** [comment]
Hey @gabriel-vasile, can I take this one?

**Comment by gabriel-vasile** [comment]
Sure!

**Comment by pippo** [comment]
@felipecaputo, are you still working on this? If not, I'd give it a try.

**Comment by felipecaputo** [comment]
@pippo sorry for taking so long.
