### ISSUE TITLE
Add support for Opendocument chart and chart template file format

### ISSUE THREAD

**Issue by gabriel-vasile** [gabriel-vasile/mimetype#126]
1) Specify the MIME type and extension for which to add support
application/x-vnd.oasis.opendocument.chart, .odc
application/vnd.oasis.opendocument.chart-template, .otc
2) Share an example file
...
3) Optionally, add a reference to the specification of the file format.
https://github.com/apache/tika/blob/86888d9cdf39455bf8bb8dda05e77e790749476b/tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml#L2085

**Comment by ibraimgm** [comment]
Can I try this one?

**Comment by gabriel-vasile** [comment]
Sure!
