### ISSUE TITLE
Repository should be named "content-type"

### ISSUE THREAD

**Issue by ex-tag** [gabriel-vasile/mimetype#134]
I'm really confused why this repo / package is named "mimetype", when it detects content-type, and it does not detect mimetype.

Mime-type
"text/plain"

Content-type
"text/plain; charset=utf-8"

Should detect mimetype, or the name of the package should be updated.

**Comment by gabriel-vasile** [comment]
> I'm really confused why this repo / package is named "mimetype"

For SEO purposes and because 99% percent of the users don't care about this kind of nuances.
