### ISSUE TITLE
Docker / use inside container

### ISSUE THREAD

**Issue by mhf-ir** [gabriel-vasile/mimetype#142]
Like gomplate: https://docs.gomplate.ca/installing/#use-inside-a-container

```Dockerfile
COPY --from=gabriel-vasile/mimetype /mimetype /bin/mimetype
RUN /bin/mimetype /bin/ls
```

**Comment by gabriel-vasile** [comment]
This project is a library. Please write import it inside a main.go and do your own command line.
Even better alternative is using the standard linux [file](https://www.man7.org/linux/man-pages/man1/file.1.html) utility.
