### ISSUE TITLE
Add support for other text encodings/charsets

### ISSUE THREAD

**Issue by vital-dhaveloose** [gabriel-vasile/mimetype#145]
Hello mr. Vasile,

we've seen that only UTF charsets are supported and that UTF-8 is returned for (for example) ISO-8859-1 encoded files (which is actually wrong).

The x/net package may help with this: https://pkg.go.dev/golang.org/x/net/html/charset#DetermineEncoding . It references the HTML standard that lists encodings that should be supported (by HTML parsing implementations that is): https://html.spec.whatwg.org/multipage/parsing.html#character-encodings

Kind regards,
Vital D'haveloose
UZ Leuven
Belgium

**Comment by gabriel-vasile** [comment]
Hi,
I looked a bit into encoding detection. There is also https://github.com/saintfish/chardet, but it works a little bit different for HTML by stripping the HTML tags and performing detection on the remaining content. 
Between the two, the approach you linked seems better.
I'll try to do something the following days.

**Comment by gabriel-vasile** [comment]
Hi, commit 6e783c349bf4fc7e0be6ff3d5886dca78be8c3ba introduces charset detection for HTML and XML documents.

I will close this issue for now. Please open another one if you have problems with the new code.
 
To test the new code, upgrade to the latest commit with:
```go
go get github.com/gabriel-vasile/mimetype@6e783c349bf4fc7e0be6ff3d5886dca78be8c3ba
```
