### ISSUE TITLE
XML encoding is fixed to UTF-8

### ISSUE THREAD

**Issue by gabriel-vasile** [gabriel-vasile/mimetype#147]
Use the `encoding` attribute to detect correct encoding.
Similar discussion as #145.

**Comment by AidanKenney** [comment]
Hey @gabriel-vasile, I'd like to take a shot at this one.

**Comment by gabriel-vasile** [comment]
Hi, I'm sorry but this issue was solved in https://github.com/gabriel-vasile/mimetype/commit/6e783c349bf4fc7e0be6ff3d5886dca78be8c3ba and I forgot to close it. 
There are still #155, #170, #171, #172 that you can look at if you want.
