### ISSUE TITLE
Improve CSV file detection

### ISSUE THREAD

**Issue by IevgenLuzan** [gabriel-vasile/mimetype#156]
1) Specify the MIME type and extension for which to add support
Add one more delimiter for csv file recognition
2) Share an example file
```
// Csv matches a comma-separated values file.
func Csv(raw []byte, limit uint32) bool {
	return sv(raw, ',') && sv(raw, ';')
}
```
3) Optionally, add a reference to the specification of the file format.
...

**Comment by gabriel-vasile** [comment]
The problem with this proposal is that [the CSV format definition](https://datatracker.ietf.org/doc/html/rfc4180#section-2) does not allow for any other delimiter, except a comma ','.
I suggest you use [`Extend`](https://pkg.go.dev/github.com/gabriel-vasile/mimetype#example-package-Extend) to make it work for your use case:
```go
csvDetector := func(raw []byte, limit uint32) bool {
	return sv(raw, ';')
}
mimetype.Extend(csvDetector, "text/csv", ".csv")
```
https://github.com/gabriel-vasile/mimetype/blob/422cc9c142c5ad536d0a2a463bf259ee0cbcca44/internal/magic/text_csv.go#L19-L28
