### ISSUE TITLE
Odd behavior on JSONL files

### ISSUE THREAD

**Issue by mkgvt** [gabriel-vasile/mimetype#173]
Expected behavior: both these files should be reported as `application/json` and `.json` ([JSONL](https://jsonlines.org/) really).

* [test1.json](https://gist.github.com/mkgvt/624805f5e03c4a88128a24b3a476f3f0#file-test1-json)
* [test2.json](https://gist.github.com/mkgvt/624805f5e03c4a88128a24b3a476f3f0#file-test2-json)

instead of:

* test1.json is reported as `application/octet-stream` and no suffix
* test2.json is reported as `text/plain; charset=utf-8` with suffix `.txt`

(It appears that the difference comes because the length of the first file is less than 512b while the length of the last file is greater than 512b.)

Attempted solution, extend `mimetype` with a specific test (which isn't general but should work for JSONL files):

```
	jsonlDetector := func(raw []byte, limit uint32) bool {
                // Non-general test that works for JSONL
		return bytes.HasPrefix(raw, []byte("{\"}"))
	}
	mimetype.Extend(jsonlDetector, "text/json", ".json")
	contentType := mimetype.Detect(buffer)
```
but that didn't work. (It seems the built-in detection logic takes precedence over extensions.)

How can one extend `mimetype` so that a more specific rule overrides less specific ones?

**Comment by gabriel-vasile** [comment]
Hi, I tested your files and got `text/plain` for both. They are reported as `text/plain` because they are not valid JSON lines.
```json
{"name:","zero","value":0}
``` 
should have been
```json
{"name":"zero","value":0}
``` 

> It seems the built-in detection logic takes precedence over extensions.

That's not the case. The rules added by Extend take precedence over the built-in ones. This [Extend](https://play.golang.org/p/ZVgrjXqv1un) example shows it.

**Comment by mkgvt** [comment]
Thanks Vasile. It is embarrassing that I missed that.
