### ISSUE TITLE
TXT files with digits are detected as json

### ISSUE THREAD

**Issue by IevgenLuzan** [gabriel-vasile/mimetype#175]
**Attach the file for which the detection is inaccurate**
[11.txt](https://github.com/gabriel-vasile/mimetype/files/6991380/11.txt)

**Expected MIME type**
txt

**Returned MIME type**
json

**Version of the library you are using**
the semver version or the hash of the commit
1.3.0
**Output of `go version`**
...
1.16.6
**Additional context**

Reproduсed with any txt file that contents just digits.

**Comment by gabriel-vasile** [comment]
It reproduces with a single string too.
I guess the fix is to return json just for files containing a json object or a json array.
Just `1234` or `"abcd"` should return txt.
This would be inline with that `file --mime 11.txt` does too.

**Comment by IevgenLuzan** [comment]
Is there any chanse override that behavior for now?
`mimetype.Extend` does not help here.
@gabriel-vasile

**Comment by gabriel-vasile** [comment]
I made the PR with the fix. If you don't want to wait until the new version is released, you can run:
```bash
go get github.com/gabriel-vasile/mimetype@dd10de59634d
```
Thank you for reporting this issue.

**Comment by IevgenLuzan** [comment]
Thank you for the quik help.
It works.
