### ISSUE TITLE
Microsoft Word detected as ZIP

### ISSUE THREAD

**Issue by hsouna** [gabriel-vasile/mimetype#180]
**Attach the file for which the detection is inaccurate**
You can use the file sharing site of your choice, just ensure the file will not expire or get deleted.
[Docume5623.docx](https://github.com/gabriel-vasile/mimetype/files/7013583/Docume5623.docx)

**Expected MIME type**
Microsoft Word 2007+ / application/vnd.openxmlformats-officedocument.wordprocessingml.document

**Returned MIME type**
application/zip

**Version of the library you are using**
1.3.1

**Output of `go version`**
go1.16.5

**Comment by gabriel-vasile** [comment]
Use [SetLimit](https://pkg.go.dev/github.com/gabriel-vasile/mimetype#SetLimit) to increase the number of bytes used for detection. For the file you provided SetLimit(4000) fixes detection, but 4000 might not be enough for other files. 

I'm thinking of increasing the default limit from 3072. This issue with Ms Office files detected as zip comes from time to time.
Btw, do you know what program was used to create that docx?

**Comment by hsouna** [comment]
Okay, I'll try that and get back to you. Thank you!
I used Onedrive to create that file. So it's the Cloud version of Microsoft Word.

**Comment by hsouna** [comment]
That fixes the problem! Thanks :smile:
