### ISSUE TITLE
Time zone info format detection could be more accurate

### ISSUE THREAD

**Issue by gabriel-vasile** [gabriel-vasile/mimetype#214]
Right now the check is:
https://github.com/gabriel-vasile/mimetype/blob/222d00f101284dcaaf19a485e02665d27fcc9728/internal/magic/binary.go#L21
This is a lot of room for false positives with this check.

Solution: 
https://tools.ietf.org/id/draft-murchison-tzdist-tzif-00.html#rfc.section.3

**Comment by n-vr** [comment]
Hello @gabriel-vasile!

I am trying to contribute more to open source projects, so I created a PR to fix this issue for you. Ofcourse, feel free to do whatever you please with it.
