### ISSUE TITLE
Tests will break with git conversion of text linebreaks on windows

### ISSUE THREAD

**Issue by zabullet** [gabriel-vasile/mimetype#22]
https://github.com/gabriel-vasile/mimetype/blob/f4632f435f6a7990b7dd3cffb32866d85ada74a5/mime_test.go#L110

Depending on git settings the beginning of _foobar.fb_ will be _foobar\n_ or _foobar\r\n_, causing the test to fail in the latter case.

Would it suffice to just have it match "foobar"?

**Comment by gabriel-vasile** [comment]
Nice find! Yes, we can loosen that check. An alternative would be to add .gitattributes and force git to use LF on checkout but this seems overkill for a dummy test. If you want to, you can add a PR, else I will make the change.

**Comment by zabullet** [comment]
I'll do a quick PR.

**Comment by gabriel-vasile** [comment]
Closed in 886370b9de2512766ffc3994e05c66599055e5ce
