### ISSUE TITLE
Read RFC and decide if application/xml is an alias for text/xml

### ISSUE THREAD

**Issue by gabriel-vasile** [gabriel-vasile/mimetype#227]
https://www.rfc-editor.org/rfc/rfc7303

**Comment by th11** [comment]
hi @gabriel-vasile - any thoughts on making this change?

**Comment by gabriel-vasile** [comment]
Page 21 in RFC:
```
   The registration information for text/xml is in all respects the same
   as that given for application/xml above ([Section 9.1](https://www.rfc-editor.org/rfc/rfc7303#section-9.1)), except that
   the "Type name" is "text".
```

So the RFC registers `application/xml` is the "main" mime type and `text/xml` is an alias. 

But in real-life usage, `text/xml` seems preferred: linux file utility and go stdlib `http.DetectContentType` don't have mime aliases, and they both exclusively use `text/xml`. OTOH, [apache tika](https://github.com/apache/tika/blob/0f5570691133c75ac4472c3340354a6c4080b104/tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml#L4928-L4934) does it the other way around :confused: 

mimetype exclusively used `text/xml` until now, so adding `application/xml` as an alias seems appropriate.
