### ISSUE TITLE
.PPT file type is being detected as .DOC

### ISSUE THREAD

**Issue by AyushJha121** [gabriel-vasile/mimetype#229]
File -  [link](https://super-teacher-dev.s3.ap-south-1.amazonaws.com/batch-feed/6020bcc9-c9e1-4263-9f8a-5b3e4e395c44-sample.ppt)
**Expected MIME type**
application/vnd.ms-powerpoint
**Returned MIME type**
application/msword

**Version of the library you are using**
github.com/gabriel-vasile/mimetype v1.4.0 h1:Cn9dkdYsMIu56tGho+fqzh7XmvY2YyGU0FnbhiOsEro=
**Output of `go version`**
go version go1.17.3 darwin/amd64

**Additional context**
Any file with .ppt extension is being detected as word document, .pptx extensions are working fine.

**Comment by gabriel-vasile** [comment]
`mimetype` looks only at the [first few bytes](https://github.com/gabriel-vasile/mimetype/blob/db2464c28aec4d6b0bf14bebba595b1ca4061d75/mimetype.go#L16-L17) and sometimes the .ppt signature is at the end of the file.
Try increasing readLimit:
```go
// increase to 1MB, default is 3KB.
mimetype.SetLimit(1024 * 1024)
mimetype.DetectFile("file.ppt")
```

**Comment by AyushJha121** [comment]
Yes this works, performance wise how much will it impact if i set the size to 5mb

**Comment by gabriel-vasile** [comment]
The slowest detection is for `text/plain` because it iterates over every character to see if it is printable.
Increasing the limit should not affect you if you don't work with many text files.

But at the end of the day this is just my gut feeling. Use benchmarks for a proper answer.
