### ISSUE TITLE
JSON content beginning in low-ascii characters is no longer detected as application/json since 1.0.1

### ISSUE THREAD

**Issue by froodian** [gabriel-vasile/mimetype#239]
**Attach the file for which the detection is inaccurate**
You can use the file sharing site of your choice, just ensure the file will not expire or get deleted.

```
{\n\t\t\"Hello\": \"World\"}
```

**Expected MIME type**

application/json

**Returned MIME type**

application/x-dbf

**Version of the library you are using**

This reproduces starting in 1.0.1 and in any version since - it was introduced by https://github.com/gabriel-vasile/mimetype/commit/798d7a4907188c172196b8901500021fb6e8154e - specifically due to txt being renamed to utf8 and moved to lowest priority

**Output of `go version`**

go version go1.17.2 darwin/amd64

**Comment by gabriel-vasile** [comment]
#241 should fix this. 

You can test it with:
```bash
go get github.com/gabriel-vasile/mimetype@272584c8
```

Let me know if there's still an issue.

**Comment by froodian** [comment]
Hi @gabriel-vasile - thanks for the fast fix and sorry for the delay - our tests are all passing with that patch so as far as I can see the issue appears fixed, thank you
