### ISSUE TITLE
Improve SVG matcher

### ISSUE THREAD

**Issue by inliquid** [gabriel-vasile/mimetype#25]
Hi,
what about "image/svg"? I think it's pretty important and simple at the same time, just consider `<svg>` tag.

**Comment by gabriel-vasile** [comment]
Hi, 
currently we detect svgs, if they have this line at the top of the document:
`<?xml version="1.0" encoding="UTF-8"?>`.

However, looking at the sources of this [stackoverflow answer](https://stackoverflow.com/a/38172170/6449978), the `xml` line above and the `doctype` line `<!DOCTYPE svg` are optional and many programs don't include them and just start with the `<svg>` tag. I will look into this issue. Thanks for pointing it out.

**Comment by inliquid** [comment]
Yep, I have few images with `<svg>` and no `<?xml>` at the beginning, would be nice to have it solved. The reason for my initial question was that  I'm using go modules by default, and latest tagged version didn't have SVG matcher, so it probably makes sense to tag it.

**Comment by gabriel-vasile** [comment]
Done, see [v0.1.1](https://github.com/gabriel-vasile/mimetype/releases/tag/v0.1.1).

**Comment by inliquid** [comment]
Thank you!

**Comment by zkip** [comment]
![image](https://user-images.githubusercontent.com/19899022/136675310-2e515165-1f5c-47aa-940c-1e5c6d4102c0.png)
Please consider the above case, the comment on the first line successfully tricks the detector. Is the situation likely to improve further ?
