### ISSUE TITLE
.shp and .shx have been registered at IANA

### ISSUE THREAD

**Issue by gabriel-vasile** [gabriel-vasile/mimetype#255]
[mimetype used `application/octet-stream` until now for these formats](https://github.com/gabriel-vasile/mimetype/blob/c6adf9ad07f1287ec8618b6b709f29cfa5acd0e8/tree.go#L190-L191).

Now that `application/vnd.shp` and `application/vnd.shx` have been registered at IANA, they can be used.
https://www.iana.org/assignments/media-types/application/vnd.shp
https://www.iana.org/assignments/media-types/application/vnd.shx

**Comment by AliAkberAakash** [comment]
Hi, I'd like to work on this.

**Comment by gabriel-vasile** [comment]
Great, this should be straight forward.

**Comment by dijotmathews** [comment]
Is there anything left to be done in this?
