### ISSUE TITLE
mimetype can"t detect some mp4

### ISSUE THREAD

**Issue by awkj** [gabriel-vasile/mimetype#26]
it will return application/octet-stream as samilar to standard libararay, if I use 	"github.com/h2non/filetype" check the movie , it will give me correct result.

```go

func Mp4(buf []byte) bool {
	return len(buf) > 11 &&
		(buf[4] == 'f' && buf[5] == 't' && buf[6] == 'y' && buf[7] == 'p') &&
		((buf[8] == 'a' && buf[9] == 'v' && buf[10] == 'c' && buf[11] == '1') ||
			(buf[8] == 'd' && buf[9] == 'a' && buf[10] == 's' && buf[11] == 'h') ||
			(buf[8] == 'i' && buf[9] == 's' && buf[10] == 'o' && buf[11] == '2') ||
			(buf[8] == 'i' && buf[9] == 's' && buf[10] == 'o' && buf[11] == '3') ||
			(buf[8] == 'i' && buf[9] == 's' && buf[10] == 'o' && buf[11] == '4') ||
			(buf[8] == 'i' && buf[9] == 's' && buf[10] == 'o' && buf[11] == '5') ||
			(buf[8] == 'i' && buf[9] == 's' && buf[10] == 'o' && buf[11] == '6') ||
			(buf[8] == 'i' && buf[9] == 's' && buf[10] == 'o' && buf[11] == 'm') ||
			(buf[8] == 'm' && buf[9] == 'm' && buf[10] == 'p' && buf[11] == '4') ||
			(buf[8] == 'm' && buf[9] == 'p' && buf[10] == '4' && buf[11] == '1') ||
			(buf[8] == 'm' && buf[9] == 'p' && buf[10] == '4' && buf[11] == '2') ||
			(buf[8] == 'm' && buf[9] == 'p' && buf[10] == '4' && buf[11] == 'v') ||
			(buf[8] == 'm' && buf[9] == 'p' && buf[10] == '7' && buf[11] == '1') ||
			(buf[8] == 'M' && buf[9] == 'S' && buf[10] == 'N' && buf[11] == 'V') ||
			(buf[8] == 'N' && buf[9] == 'D' && buf[10] == 'A' && buf[11] == 'S') ||
			(buf[8] == 'N' && buf[9] == 'D' && buf[10] == 'S' && buf[11] == 'C') ||
			(buf[8] == 'N' && buf[9] == 'S' && buf[10] == 'D' && buf[11] == 'C') ||
			(buf[8] == 'N' && buf[9] == 'D' && buf[10] == 'S' && buf[11] == 'H') ||
			(buf[8] == 'N' && buf[9] == 'D' && buf[10] == 'S' && buf[11] == 'M') ||
			(buf[8] == 'N' && buf[9] == 'D' && buf[10] == 'S' && buf[11] == 'P') ||
			(buf[8] == 'N' && buf[9] == 'D' && buf[10] == 'S' && buf[11] == 'S') ||
			(buf[8] == 'N' && buf[9] == 'D' && buf[10] == 'X' && buf[11] == 'C') ||
			(buf[8] == 'N' && buf[9] == 'D' && buf[10] == 'X' && buf[11] == 'H') ||
			(buf[8] == 'N' && buf[9] == 'D' && buf[10] == 'X' && buf[11] == 'M') ||
			(buf[8] == 'N' && buf[9] == 'D' && buf[10] == 'X' && buf[11] == 'P') ||
			(buf[8] == 'N' && buf[9] == 'D' && buf[10] == 'X' && buf[11] == 'S') ||
			(buf[8] == 'F' && buf[9] == '4' && buf[10] == 'V' && buf[11] == ' ') ||
			(buf[8] == 'F' && buf[9] == '4' && buf[10] == 'P' && buf[11] == ' '))
}
```
```go
// Mp4 matches an MP4 file.
func Mp4(in []byte) bool {
	if len(in) < 12 {
		return false
	}

	mp4ftype := []byte("ftyp")
	mp4 := []byte("mp4")
	boxSize := int(binary.BigEndian.Uint32(in[:4]))
	if boxSize%4 != 0 || len(in) < boxSize {
		return false
	}
	if !bytes.Equal(in[4:8], mp4ftype) {
		return false
	}
	for st := 8; st < boxSize; st += 4 {
		if st == 12 {
			// minor version number
			continue
		}
		if bytes.Equal(in[st:st+3], mp4) {
			return true
		}
	}

	return false
}
```

I found the two core code, Can I Use the way to fix？

**Comment by gabriel-vasile** [comment]
`mimetype` uses the algorithm defined [here](https://mimesniff.spec.whatwg.org/#signature-for-mp4) for mp4 detection. However, it looks like our implementation of the algorithm is not up to date with the specification (step 7 is missing). Maybe updating to the latest specification will fix this issue. If it doesn't fix the issue, we can have a look at how `filetype` detects mp4.

Also, please attach an example of an mp4 file which does not pass. I downloaded mp4s from different sources but could not find one.

**Comment by awkj** [comment]
> `mimetype` uses the algorithm defined [here](https://mimesniff.spec.whatwg.org/#signature-for-mp4) for mp4 detection. However, it looks like our implementation of the algorithm is not up to date with the specification (step 7 is missing). Maybe updating to the latest specification will fix this issue. If it doesn't fix the issue, we can have a look at how `filetype` detects mp4.
> 
> Also, please attach an example of an mp4 file which does not pass. I downloaded mp4s from different sources but could not find one.

thanks your answer, 

this is a sample :https://video.youpin.mi-img.com/staging/test/f632441a334fea7cbd6201d345970dab.mp4,

wish can help you to fix ,I try to see the link.

**Comment by gabriel-vasile** [comment]
I had a look at the attached file and I think we should stop using this [specification](https://mimesniff.spec.whatwg.org/#signature-for-mp4) because it clearly does not detect files like the one you sent.

Instead we should create a matcher similar to `filetype`. You can submit a pull request with the changes if you want to.
Another reference you can use when writing the matcher is [file](https://github.com/file/file/blob/97330b020551a6bafbc6b14161428d805b232c2a/magic/Magdir/animation). I tested `file` on my computer and it matches mp4s correctly.
