### ISSUE TITLE
Possible enhancement

### ISSUE THREAD

**Issue by gerardmrk** [gabriel-vasile/mimetype#27]
I noticed all of the matchers had their file signatures defined inline and was curious if hoisting them to global scope would make any difference. Turns out for huge files it makes a significant difference. Of course would have to take into consideration whether to sacrifice memory over speed since all signatures stored in global vars would be stored on the heap.

### Benchmark Source

```go

...

var dataPdf []byte

func init() {
	dataPdf, _ = ioutil.ReadFile("../testdata/a.pdf")
}

var sigPdf = []byte{0x25, 0x50, 0x44, 0x46}

func PdfAlt(in []byte) bool {
	return bytes.Equal(in[:4], sigPdf)
}

func Benchmark_Pdf(b *testing.B) {
	for i := 0; i < b.N; i++ {
		Pdf(dataPdf)
	}
}

func Benchmark_PdfAlt(b *testing.B) {
	for i := 0; i < b.N; i++ {
		PdfAlt(dataPdf)
	}
}

```

### Benchmark Result

```
goos: darwin
goarch: amd64
pkg: github.com/gabriel-vasile/mimetype/matchers
Benchmark_Pdf-8         200000000                6.27 ns/op
Benchmark_PdfAlt-8      500000000                3.56 ns/op
PASS
ok      github.com/gabriel-vasile/mimetype/matchers     4.075s
```

### Benchmark Source

```go
...

var dataPng []byte

func init() {
	dataPng, _ = ioutil.ReadFile("../testdata/a.png")
}

var sigPng = []byte{0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A}

func PngAlt(in []byte) bool {
	return bytes.Equal(in[:8], sigPng)
}

func Benchmark_Png(b *testing.B) {
	for i := 0; i < b.N; i++ {
		Png(dataPng)
	}
}

func Benchmark_PngAlt(b *testing.B) {
	for i := 0; i < b.N; i++ {
		PngAlt(dataPng)
	}
}

```

### Benchmark Result

```
goos: darwin
goarch: amd64
pkg: github.com/gabriel-vasile/mimetype/matchers
Benchmark_Png-8         500000000                3.13 ns/op
Benchmark_PngAlt-8      500000000                3.11 ns/op
PASS
ok      github.com/gabriel-vasile/mimetype/matchers     3.767s
```

**Comment by gabriel-vasile** [comment]
Interesting catch but I'm not sure the size of the file makes a difference. Between the PDF and PNG case, there is also the length of the signature which might affect the result. Could it be that the length of the signature is the reason why the PDF saw such a great improvement, while PNG remained almost the same?

**Comment by gabriel-vasile** [comment]
I have created a few benchmarks to test if the length of the signature affects the performance of hoisted and inlined functions. The code is [here](https://github.com/gabriel-vasile/mimetype/blob/hoisted_bench/matchers/matchers_test.go).
I have created signatures of 1, 10, 100 and 1000 bytes length, both hoisted and inline. All the of the signatures fail to match the test data.
### The results of the benchmark
```goos: linux
goarch: amd64
pkg: github.com/gabriel-vasile/mimetype/matchers
Benchmark_Sig1Byte-24          	200000000	         6.18 ns/op	       0 B/op	       0 allocs/op
Benchmark_Sig1ByteAlt-24       	500000000	         3.57 ns/op	       0 B/op	       0 allocs/op
Benchmark_Sig10Byte-24         	500000000	         3.35 ns/op	       0 B/op	       0 allocs/op
Benchmark_Sig10ByteAlt-24      	500000000	         3.06 ns/op	       0 B/op	       0 allocs/op
Benchmark_Sig100Byte-24        	200000000	        10.7 ns/op	       0 B/op	       0 allocs/op
Benchmark_Sig100ByteAlt-24     	300000000	         4.17 ns/op	       0 B/op	       0 allocs/op
Benchmark_Sig1000Byte-24       	50000000	        23.3 ns/op	       0 B/op	       0 allocs/op
Benchmark_Sig1000ByteAlt-24    	300000000	         4.22 ns/op	       0 B/op	       0 allocs/op
```
Hoisting seems to improve the performance compared to the inline signature across all the lengths of signatures.
The weird case for me is `Benchmark_Sig1Byte` which has worse performance than the 10 bytes signature. I would have expected the performance to drop when the length is increased, which is the case for length of 10, 100 and 1000. I really can't find a reason why 1 byte length is so slow. Any idea?

**Comment by gerardmrk** [comment]
Yeah nah you're right it has nothing to do with the file size itself I didn't even bother to look closely at the `in[:8]` part before commenting sorry. With regards to the poor performance on the first result, I'm not sure either, is it consistently worse?

Just something to consider if you were thinking about adding them to global scope, inlining the signatures means they only get "loaded" when the function gets called. If we add them all to the global scope, they're going to be unconditionally loaded each run, regardless of whether the user needs them or not. That's a lot of signatures. I personally I prefer the speed and am willing to sacrifice other resource usage for it, but others who are using this lib may not be happy with that option
