### ISSUE TITLE
Make recycleReader an external function

### ISSUE THREAD

**Issue by eccles** [gabriel-vasile/mimetype#281]
The function:

        recycleReader(input io.Reader) (mimeType string, recycled io.Reader, err error)

in mime_test.go is extremely useful and should be made available.

**Comment by gabriel-vasile** [comment]
I feel that this function is outside the scope of the library. 
Also, if someone calls the function with a `io.ReadCloser` they will receive back a `io.Reader` which they cannot close anymore. 
Better for users to handle the situation themselves.
