### ISSUE TITLE
Add support for GeoJSON file format

### ISSUE THREAD

**Issue by AntoineGirard** [gabriel-vasile/mimetype#29]
1) Specify the MIME type and extension for which to add support

- MIME type : application/geo+json
- Extension : geojson

2) Share an example file

```json
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "name": "Dinagat Islands"
  }
}
```
Example of the official website.

3) Optionally, add a reference to the specification of the file format.

- [RFC 7946](https://tools.ietf.org/html/rfc7946)
- [Website](http://geojson.org/) 

TIA ;)

**Comment by gabriel-vasile** [comment]
Hi, thanks for the suggestion. See [v0.3.2](https://github.com/gabriel-vasile/mimetype/releases/tag/v0.3.2).

**Comment by AntoineGirard** [comment]
Thanks 👍
