### ISSUE TITLE
Add support for CSV file format

### ISSUE THREAD

**Issue by AntoineGirard** [gabriel-vasile/mimetype#30]
1) Specify the MIME type and extension for which to add support

- MIME type : text/csv
- extension : csv

2) Share an example file

From specification : 
```csv
date,temperature,place
2011-01-01,1,Galway
2011-01-02,-1,Galway
2011-01-03,0,Galway
2011-01-01,6,Berkeley
2011-01-02,8,Berkeley
2011-01-03,5,Berkeley
```

3) Optionally, add a reference to the specification of the file format.

- Specification [RFC 7111](https://tools.ietf.org/html/rfc7111)

TIA ;)

**Comment by gabriel-vasile** [comment]
Hello! [v0.3.4](https://github.com/gabriel-vasile/mimetype/releases/tag/v0.3.4) is out with support for CSV and TSV.
