### ISSUE TITLE
There might be a new mov file signature in ios 15.5 livp

### ISSUE THREAD

**Issue by Cherryslover** [gabriel-vasile/mimetype#302]
**Attach the file for which the detection is inaccurate**
Unfortunately, I don't have an iPhone to provide one. This seems come out with the ios 15.5. The mov file of live photo sometimes are detected as "application/octet-stream", sometimes are "video/quicktime".

**Expected MIME type**
video/quicktime

**Returned MIME type**
application/octet-stream

**Version of the library you are using**
v1.4.1

**Output of `go version`**
1.16.7

**Additional context**

Alternatively, you can fork the project, commit the file with a failing test and reference the commit in the issue.

**Comment by gabriel-vasile** [comment]
Just to make sure there is no misunderstanding what is happening:
case 1: the exact same file is sometimes detected as `video/quicktime` and other times as `application/octet-stream`
case 2: some `.mov` files are detected correctly as `video/quicktime` and others are not?

What case are we in?

**Comment by Cherryslover** [comment]
We are in case 2, they are different files.

**Comment by Cherryslover** [comment]
I can give first 20 bytes. _00 00 00 08 77 69 64 65 00 5A 16 6A 6D 64 61 74 00 00 00 2A_.

Something interesting is that I found 00 00 00 08 77 69 64 65 in a normal mov file(detected as video/quicktime) at offset 21. But when I cut a normal mov file first 20 bytes off, the mov cannot be played. So I wonder if it is a new file signature.

**Comment by gabriel-vasile** [comment]
Thanks! 
You're right, there are some missing signatures for `mov` files. 
These are [quicktime signatures in Apache Tika](https://github.com/apache/tika/blob/598015bbbeaa65026a48a6abeb7adfb40e2c9bc8/tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml#L7758-L7777). The signature which identifies your file is on line 7772.

I will make a commit the following days.

**Comment by Cherryslover** [comment]
Glad that helped :)
