### ISSUE TITLE
Add support for Shapefile file format

### ISSUE THREAD

**Issue by AntoineGirard** [gabriel-vasile/mimetype#31]
1) Specify the MIME type and extension for which to add support

Shapefile is a little bit complex because you need to manage multiples files. For a Shapefile you have 3 _mandatory_ files : 

- .shp (application/octet-stream)
- .dbf (application/x-dbf)
- .shx (application/octet-stream)

I think it could be a good thing to add this 3 types of files in mimetype.

2) Share an example file

You can find examples [here](http://download.geofabrik.de/europe.html)

3) Optionally, add a reference to the specification of the file format.

- [Shapefile Wikipedia Page](https://en.wikipedia.org/wiki/Shapefile)
- [dBase Wikipedia Page](https://en.wikipedia.org/wiki/Shapefile)
- [Shapefile Specifications](https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf)

**Comment by gabriel-vasile** [comment]
Hi! I published [v0.3.3](https://github.com/gabriel-vasile/mimetype/releases/tag/v0.3.3) :)

**Comment by AntoineGirard** [comment]
Thanks! 👌
