### ISSUE TITLE
Invalid MIME type for msword document

### ISSUE THREAD

**Issue by strider2038** [gabriel-vasile/mimetype#33]
**Attach the file for which the detection is inaccurate**

https://github.com/strider2038/mimetype/commit/4678076d99a9a462c42069644906225a63a5f57d

**Expected mime type**

application/msword

**Returned mime type**

application/octet-stream

**Output of `go version`**

go version go1.12.3 linux/amd64

**Comment by gabriel-vasile** [comment]
Fixed in [v0.3.11](https://github.com/gabriel-vasile/mimetype/releases/tag/v0.3.11). Thanks for reporting it.

**Comment by strider2038** [comment]
@gabriel-vasile thanks, our problem was solved with this fix.
