### ISSUE TITLE
XML file incorrectly getting matched as text/plain

### ISSUE THREAD

**Issue by melissafzhang** [gabriel-vasile/mimetype#38]
**Attach the file for which the detection is inaccurate**
You can use the file sharing site of your choice, just ensure the file will not expire or get deleted.

**Expected mime type**
text/xml; charset=utf-8

**Returned mime type**
text/plain

**Output of `go version`**
go 1.12

**Additional context**
```
<resources>
    <string name="scan_tabs_left_button">Scan code</string>
    <string name="scan_tabs_right_button">My address</string>
    <string name="my_address">My Address</string>
    <string name="addresses_copied">Copied to clipboard.</string>
    <string name="copy_address">Copy Address</string>
</resources>
```

**Comment by gabriel-vasile** [comment]
The example text is just a fragment of a XML file. Detecting it as text/plain is correct because it misses the `<?xml>` tag. [file](https://github.com/file/file) and [tika](https://github.com/apache/tika/) also detect this as text/plain.
