### ISSUE TITLE
panic error="runtime error: slice bounds out of range" while match for geo json

### ISSUE THREAD

**Issue by MoonJustry** [gabriel-vasile/mimetype#39]
**Attach the file for which the detection is inaccurate**
while call DetectReader or DetectFile while the in 2048（matchers.ReadLimit） bytes starts with '{' and ends with "type" like in[0] = '{' and in[2042:] = "type" or call Detect like this case, panic~~

**Expected mime type**
application/json

**Returned mime type**
panic

**Output of `go version`**
go1.12.4

**Additional context**
.

function GeoJson looks like it should check slice bounds is discussed，and node.match to recovery panic, Instead of throwing exceptions directly to the caller

**Comment by gabriel-vasile** [comment]
Hi! I was able to reproduce the problem and published a release to fix the panic.

**Comment by MoonJustry** [comment]
👍
