### ISSUE TITLE
Add support for NDJSON file format

### ISSUE THREAD

**Issue by gabriel-vasile** [gabriel-vasile/mimetype#40]
1) Specify the MIME type and extension for which to add 
MIME type: application/x-ndjson
extension: .ndjson
2) Share an example file
```
 {"some":"thing"}
 {"foo":17,"bar":false,"quux":true}
 {"may":{"include":"nested","objects":["and","arrays"]}}
```
3) Optionally, add a reference to the specification of the file format.
[https://github.com/ndjson/ndjson-spec](https://github.com/ndjson/ndjson-spec)

**Comment by divyanshgaba** [comment]
Hi!
I would like to help with this one. 
This is will be my very first contribution to an open-source project, hoping you could guide me if needed.

**Comment by gabriel-vasile** [comment]
Hi @divyanshgaba ! 
The algorithm seems good with one addition:

When detecting a file, the library limits itself to reading only the first [2048](https://github.com/gabriel-vasile/mimetype/blob/master/internal/matchers/matchers.go#L6) bytes from the input. Because of this, it might happen that the last split is missing some data to be valid JSON. In this case we should return true. 
This is similar to [JSON](https://github.com/gabriel-vasile/mimetype/blob/master/internal/matchers/text.go#L148) detection: The input is scanned. If there is no error, or the error happens at the 2048th byte then we consider this is a JSON file that might have been cut at 2048 bytes. Else, if the error happened before reaching the ReadLimit, return false.

**Comment by divyanshgaba** [comment]
Understood! Should i start working on this?

**Comment by gabriel-vasile** [comment]
Yeah, sure!

**Comment by divyanshgaba** [comment]
I have raised a pull request https://github.com/gabriel-vasile/mimetype/pull/41, Kindly review.
