### ISSUE TITLE
Add support for Mach-O Fat file format

### ISSUE THREAD

**Issue by gabriel-vasile** [gabriel-vasile/mimetype#44]
1) Specify the MIME type and extension for which to add support
MIME type: application/x-mach-binary; extension: none
2) Share an example file
...
3) Optionally, add a reference to the specification of the file format.
It is the same MIME type as Mach-O files. The difference is it has different signature.

**Comment by terev** [comment]
https://github.com/threatstack/libmagic/blob/master/magic/Magdir/cafebabe is the libmagic rule file used to distinguish between the two file types
