### ISSUE TITLE
Detection in boundary...

### ISSUE THREAD

**Issue by UnveilTech** [gabriel-vasile/mimetype#456]
Hi All,
how do you detect when the data is a boundary multipart ?
**sample**:
------WebKitFormBoundarya3uIu5At8esasnX1
Content-Disposition: form-data; name="fileToUpload"; filename="example.pdf"
Content-Type: application/pdf

%PDF-1.4
%Çì¢
blablablabla, ..................

thanks,
Fred.

**Comment by gabriel-vasile** [comment]
I'm assuming your html looks like this:
```html
<form method="post" enctype="multipart/form-data">
  <input id="file" name="file" type="file" />
  <button>Upload</button>
</form>
```

Then the go code that will detect that file should be something like this:
```go
func httpHandler(w http.ResponseWriter, r *http.Request) {
	r.ParseMultipartForm(32 << 20)
	file, _, err := r.FormFile("file")
	if err != nil {
		panic(err)
	}
	defer file.Close()
	// file is an io.Reader so you can pass it as argument to mimetype.DetectReader
	fmt.Println(mimetype.DetectReader(file))
}
```
