### ISSUE TITLE
Add support for WARC file format

### ISSUE THREAD

**Issue by gabriel-vasile** [gabriel-vasile/mimetype#46]
1) Specify the MIME type and extension for which to add support
application/warc, .warc
2) Share an example file
[examples](https://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/#annex-b-informative-examples-of-warc-records)
3) Optionally, add a reference to the specification of the file format.
[specification](https://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1)

**Comment by lokucrazy** [comment]
Hi if no one has taken this I'll give it a try.

**Comment by gabriel-vasile** [comment]
Hi @lokucrazy , sure, you can have a go at it.

**Comment by ibraimgm** [comment]
I created PR #50 that (hopefully) solves this issue.
