### ISSUE TITLE
Add support for io.Writer

### ISSUE THREAD

**Issue by ivanjaros** [gabriel-vasile/mimetype#480]
I could really use implementation allowing me to detect mime type of incoming data, like when a file is being uploaded so that I do not have to then rewind the file and process it again with DetectReader.

So the mime writer should simply keep witting into internal buffer until some sane limit or until it can detect the mime type. After that it should be just NOOP. This could be then used with io.MultiWritter where I could write the incoming data into a file on the disk but also detect the mime type along the way since I already have access to all the bytes.

Something like:
```
type Writer struct {
	buff []byte
	res *MIME
}

func (w *Writer) Write(p []byte) (int64, error) {
	if w.res == nil {
		w.buff = append(w.buff, p...) // this should be buffer pool with fixed max capacity
		if result := root.match(w.buff, len(w.buff)); result != nil {
			w.res = result
			w.buff = nil // or return to pool
		}
	}
	return len(p), nil
}

func (w *Writer) Detect() *MIME {
	return w.res
}

dstW, _ := os.CreateFile("foo.txt")
mimeW := new(Writer)
w := io.MultiWriter(dstW, mimeW)
io.Copy(w, src)
```

**Comment by gabriel-vasile** [comment]
You can achieve something similar by using a byte buffer, [io.TeeReader](https://pkg.go.dev/io#TeeReader), and [io.MultiReader](https://pkg.go.dev/io#MultiReader).

The code would look something like this:
```go
dstW, _ := os.CreateFile("foo.txt")
header := bytes.NewBuffer(nil)
mtype, _ := mimetype.DetectReader(io.TeeReader(src, header))

src = io.MultiReader(header, src)
// src now contains the complete, original data.
```

There is [an example in docs](https://pkg.go.dev/github.com/gabriel-vasile/mimetype#example-package-DetectReader). 

Let me know if this solves the problem.

**Comment by ivanjaros** [comment]
I was talking about writing, not reading. Very different situation with less options to be creative.

**Comment by gabriel-vasile** [comment]
Sorry, I don't see what's missing for streams. I think my suggestion covers your requirement of no seeks and copying the readily available data to the destination file.

In any case, a `mimetype.Writer` will likely not happen because it's not really writer behaviour (it does not copy some data to a destination like `zip.Writer`, `bufio.Writer` or any other writer in stdlib.)

Feel free to explain the shortcomings of current situation and I will re-open the issue.

**Comment by jonathongardner** [comment]
Sorry if this isnt the right place (though you say to comment on here) but I was about to open a ticket asking for this too. I commonly want to find the filetype while I am calculating checksums so being able to use a `io.MultiWriter` is helpful. Your suggestion would copy the whole file/stream into memory though right? Though I agree there are simple work arounds (what is the ticket is like 15 lines?). My issue is now I have copied that work around to a couple of different project, it would be nice to for it to be part of the package so I (and others who need this) dont have to do that.

Also you said its not a `io.Writer` cause it doesn't copy data to a destination, but I don't think `hash.Hash` copies data to "another" location, so doesnt seem much different than that
