### ISSUE TITLE
Can't use v1.4.4 due to a "trojan"

### ISSUE THREAD

**Issue by jerbob92** [gabriel-vasile/mimetype#538]
My virusscanner blocks v1.4.4 of this package due to it containing a trojan.

You can see the VirusTotal results here: https://www.virustotal.com/gui/file/f00deb54ef962ad59bae824216aa1d160133c3a3ce669db9463e1de966729a24?nocache=1

Is there any way to get around this? Is there some file in there to test against an [Archbomb](https://encyclopedia.kaspersky.com/knowledge/trojan-arcbomb/)?

**Comment by gabriel-vasile** [comment]
Hi, it probably complains about one or more files from [testdata](https://github.com/gabriel-vasile/mimetype/tree/master/testdata) folder.

VirusTotal says something about trojan.zip, but the [gzip](https://github.com/gabriel-vasile/mimetype/blob/master/testdata/gz.gz) file seems clean. 
I will try to work on this, but no promises.
If you feel like helping, please identify the offending file/s from testdata and I will replace them.

**Comment by jerbob92** [comment]
I have tried the previous version and that doesn't list the Archbomb:  https://www.virustotal.com/gui/file/406883c1b971bf560f6e87960c4493835ea016c1a8275353f8c547cf815ef216?nocache=1 

When comparing the two versions, only the following file has been added to tesdata:
testdata/tar.issue464.tar

**Comment by gabriel-vasile** [comment]
Ah, right... [issue 464](https://github.com/gabriel-vasile/mimetype/issues/464) added detection for a tarbomb.

Let me see what I can do to remove the file but still keep the testcase.

**Comment by jerbob92** [comment]
@gabriel-vasile thanks for fixing! Would you mind rolling a release?

**Comment by gabriel-vasile** [comment]
@jerbob92  https://github.com/gabriel-vasile/mimetype/releases/tag/v1.4.5
