### ISSUE TITLE
下載v1.44被偵測是木馬

### ISSUE THREAD

**Issue by aether123** [gabriel-vasile/mimetype#556]
go\pkg\mod\cache\download\github.com\gabriel-vasile\mimetype\@v\v1.4.4.zip//github.com/gabriel-vasile/mimetype@v1.4.4/testdata/tar.issue464.tar//r\r.tar.gz
經原廠分析回覆判定結果為 病毒「UDS:Trojan-ArcBomb.GZip.Agent.e」
怎麼處理

**Comment by gabriel-vasile** [comment]
Fixed: https://github.com/gabriel-vasile/mimetype/releases/tag/v1.4.5
