### ISSUE TITLE
feat/docs: add which version supports which go version

### ISSUE THREAD

**Issue by 9ssi7** [gabriel-vasile/mimetype#557]
I want to use version 1.4.4 of this repo but when I install this version for version 1.17 of go (since the bytes.Cut function is included, extra: bytes.Cut came with version 1.18 of go [check for details](https://pkg.go.dev/bytes#Cut)) I get an error.

For this, a table showing which version works in which go version would be good.

**Comment by 9ssi7** [comment]
the table might look like this:

|Repo Version|Available Go Version|
|-------------|---------------------|
| `1.4.4`          | `>= 1.18` |
| `1.3.4`          | `< 1.18` |

**Comment by gabriel-vasile** [comment]
@9ssi7, please use the version registered in go.mod: https://github.com/gabriel-vasile/mimetype/blob/2998a94e1b488475165fb2c4f00d1a6d497289f7/go.mod#L3

It's not as convenient as your proposed method, but it's less error prone (I will most likely forget to update docs when I update go.mod).
