### ISSUE TITLE
CVEs in stdlib in current Go version 1.20

### ISSUE THREAD

**Issue by chkp-erezca** [gabriel-vasile/mimetype#601]
There are many CVEs (~180+) reported for stdlib which is used in sample32.macho and sample64.macho test files you have.
These CVEs start from Go 1.13 and you are using Go 1.20. Upgrading to 1.22.7 or above should solve all these CVEs. Is it possible to upgrade the Go version or alternatively change the relevant test files to use some other library with no CVEs? 
Attaching screenshots with part of the CVE list.
![image](https://github.com/user-attachments/assets/3a1a8e2d-8c74-4870-9b08-fd5f3d34f654)
![image](https://github.com/user-attachments/assets/91c2bbf8-0cfd-4d24-8f74-72298fb5b675)

**Comment by AndrewYEEE** [comment]
@gabriel-vasile hello. hope fix this problem, thank you><
