### ISSUE TITLE
MIME TYPE for .txt Files Fails

### ISSUE THREAD

**Issue by chahat-agarwal** [gabriel-vasile/mimetype#609]
**Attach the file for which the detection is inaccurate**
https://github.com/gabriel-vasile/mimetype/blob/master/testdata/utf8.txt

**Expected MIME type**
"text/plain"

**Returned MIME type**
"application/octet-stream"

**Version of the library you are using**
github.com/gabriel-vasile/mimetype v1.4.3

**Output of `go version`**
go 1.22.0

**Additional context**
Tried with different text files still the Detect Func returns "application/octet-stream"
<img width="701" alt="Screenshot 2024-11-13 at 8 51 56 PM" src="https://github.com/user-attachments/assets/3d101593-9837-4db1-aec5-ec6bbdeb26f1">

**Comment by gabriel-vasile** [comment]
@chahat-agarwal 
That file is used in tests and tests are passing.
https://github.com/gabriel-vasile/mimetype/blob/575b7612d9276ca3c6d82260b592bfbadabb88f0/mimetype_test.go#L240


Please provide a short `main.go` file that reproduces the problem if you think it's a problem with mimetype. 
I will check if you provide some code that reproduces the problem.

**Comment by sverma-m** [comment]
Hi @gabriel-vasile,
The issue occurs when the limit is set to a higher value as mimetype.SetLimit(1024*1024) with the same test file and the file is read using the Read with byte slice of length same as limit.
Test file: https://github.com/gabriel-vasile/mimetype/blob/master/testdata/utf8.txt
