### ISSUE TITLE
pzstd file is not detected as zstd

### ISSUE THREAD

**Issue by Koyorice** [gabriel-vasile/mimetype#619]
**Attach the file for which the detection is inaccurate**
[test.zip](https://github.com/user-attachments/files/18141160/test.zip)
test.txt.zst uses zstd
test2.txt.zst uses pzstd

**Expected MIME type**
`application/zstd`

**Returned MIME type**
`application/octet-stream`

**Version of the library you are using**
`v1.4.7`

**Output of `go version`**
`go version go1.23.4 linux/amd64`

**Additional context**
https://github.com/facebook/zstd
Files created using pzstd are not detection correctly, if use `file` command both will be detected as `application/zstd`

**Comment by gabriel-vasile** [comment]
Thank you!

**Comment by Koyorice** [comment]
Thank you too!
