### ISSUE TITLE
Not able to detect xls file

### ISSUE THREAD

**Issue by devendra1102** [gabriel-vasile/mimetype#62]
https://file-examples.com/wp-content/uploads/2017/02/file_example_XLS_10.xls

application/vnd.ms-excel

application/msword

https://github.com/gabriel-vasile/mimetype  master branch

go version go1.11.2 linux/amd64
.

**Comment by gabriel-vasile** [comment]
Hi @devendra1102 , I'm now testing some to make xls, ppt and doc detection more comprehensive. One issue that will persist even after these changes is that detection, when using `DetectReader` and `DetectFile`, is limited to the first [2048](https://github.com/gabriel-vasile/mimetype/blob/a8c8aa162272bb53454d8bcd947a244fcac916d6/internal/matchers/matchers.go#L6) bytes and this kind of files sometimes have their signature towards the end of the file.
However, if you use `Detect` and pass the whole file to it, it should be correctly detected.

**Comment by gabriel-vasile** [comment]
Hi @devendra1102 , this should be fixed, please check out the latest commit in master.
