### ISSUE TITLE
Add support for Microsoft PUB file format

### ISSUE THREAD

**Issue by gabriel-vasile** [gabriel-vasile/mimetype#65]
1) Specify the MIME type and extension for which to add support
application/vnd.ms-publisher, .pub

2) Share an example file
samples can be found online

3) Optionally, add a reference to the specification of the file format.
[magic](https://github.com/file/file/blob/48a6c295610ecc2294370798e1c1c2c7e87b5b3a/magic/Magdir/ole2compounddocs#L327)

**Comment by pippo** [comment]
I'd like to give this a try
