### ISSUE TITLE
Add support for Microsoft Access file format

### ISSUE THREAD

**Issue by gabriel-vasile** [gabriel-vasile/mimetype#66]
1) Specify the MIME type and extension for which to add support
application/x-msaccess, .accdb

2) Share an example file
can be found online

3) Optionally, add a reference to the specification of the file format.
[magic](https://github.com/file/file/blob/c97b6d3cf7c738f566f6eb313da08c7e18fbe98e/magic/Magdir/database#L458)

**Comment by pippo** [comment]
Can I give this a try?
