### ISSUE TITLE
Add support for Ventuz file format

### ISSUE THREAD

**Issue by AlaNDGT** [gabriel-vasile/mimetype#69]
1) Specify the MIME type and extension for which to add support
_Note: The MIME are just suggestion as I don't think there's any define for it._
a) `application/ventuz-scene` & `.vzs`
b) `application/ventuz-scene-archive` & `.vza`
2) Share an example file
More samples can be found [here](https://forum.ventuz.com/viewforum.php?f=14&sid=2e629a7422f29b83517bcbfd5183827b)
Samples for .vzs:
[Sample 1](https://forum.ventuz.com/download/file.php?id=693)
[Sample 2](https://forum.ventuz.com/download/file.php?id=701)
Samples for .vza:
[Sample 1](https://drive.google.com/folderview?id=0B1yZCFRGImcuUmF0LU9WMDd5NGM&usp=sharing)
[Sample 2](https://forum.ventuz.com/download/file.php?id=842)
3) Optionally, add a reference to the specification of the file format.
https://www.ventuz.com/support/help/latest/VentuzFileTypes.html?itm=14

Is that something feasible?

**Comment by thinkofher** [comment]
I can't find specifications for this file formats anywhere. Given reference contains only end user related things.

**Comment by AlaNDGT** [comment]
Yeah, I don't think you'll find any, it's proprietary to Ventuz. Probably something not feasible?

**Comment by gabriel-vasile** [comment]
ventuz is still not registered at [IANA](https://www.iana.org/assignments/media-types/media-types.xhtml) so I'll close.
