### ISSUE TITLE
Only read first 261 bytes of file?

### ISSUE THREAD

**Issue by rcoreilly** [gabriel-vasile/mimetype#7]
I noticed that DetectReader is calling ReadAll -- could get expensive -- per the filetype package, https://github.com/h2non/filetype, shouldn't you be able to just do something like this:

 // We only have to pass the file header = first 261 bytes
  head := make([]byte, 261)
  file.Read(head)

**Comment by gabriel-vasile** [comment]
For the moment the limitation cannot be removed because it would break the matching for ms office files. As soon as those functions stop using the full file for detection, the limit can be set in place.

**Comment by rcoreilly** [comment]
looks like you're now just reading the first 520 bytes and can close this?  In my tests, it is now comparably fast as the h2non/filetype
