### ISSUE TITLE
Add support for CAB file format

### ISSUE THREAD

**Issue by gabriel-vasile** [gabriel-vasile/mimetype#71]
1) Specify the MIME type and extension for which to add support
application/vnd.ms-cab-compressed, .cab
2) Share an example file
[sample.cab](http://www.file.fyicenter.com/b/sample.cab)
3) Optionally, add a reference to the specification of the file format.
[microsoft.com](https://docs.microsoft.com/en-us/previous-versions//bb267310(v=vs.85)?redirectedfrom=MSDN)

**Comment by thinkofher** [comment]
I'll take it. It will be my first ever contribution to open source!

**Comment by aporcupine** [comment]
This should probably be closed. :)
