### ISSUE TITLE
.zip incorrectly detected as .xlsx

### ISSUE THREAD

**Issue by bodgit** [gabriel-vasile/mimetype#72]
**Attach the file for which the detection is inaccurate**
Tricky, as the file is copyrighted material, however the problem is fairly obvious.

**Expected mime type**
application/zip (.zip)

**Returned mime type**
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet (.xlsx)

**Version of the library you are using**
0.3.21

**Output of `go version`**
go version go1.13.1 darwin/amd64

**Additional context**
It looks like the detection code is looking for the string/bytes "xl/" anywhere in the file when I'm guessing the intent is to look for a file path in the TOC with that directory, I can see in the problem file that it just happens to contain those 3 bytes as part of the compressed data.

**Comment by gabriel-vasile** [comment]
Hi, can you please paste the output of 
`file --mime thefile.zip`
libmagic has a slightly different detection that could be ported to `mimetype` if it works correctly.

**Comment by bodgit** [comment]
Hi, `file --mime ...` reports the file as `application/zip; charset=binary`. Looking at what libmagic does, it seems to have some extra logic about the zip format and parsing the TOC.

**Comment by gabriel-vasile** [comment]
Hi, I pushed a fix to branch `fix_msoxml`.
Please run `go get github.com/gabriel-vasile/mimetype@fix_msoxml` and confirm it fixes this issue.
I will then merge it and make a release out of it.

**Comment by bodgit** [comment]
Sorry, I completely forgot to test this. I will check later today and get back to you.

**Comment by bodgit** [comment]
Right, finally tested. That seems to work fine, the zip file is now correctly detected as a zip.

**Comment by gabriel-vasile** [comment]
Great! [v0.3.23](https://github.com/gabriel-vasile/mimetype/releases/tag/v0.3.23) has the updated code.
