### ISSUE TITLE
[Question] Handle MIME aliases ?

### ISSUE THREAD

**Issue by ppai-plivo** [gabriel-vasile/mimetype#74]
Just leaving some thoughts here about a use-case that we have...

We use `mimetype` library to detect if declared (via `Content-Type` header) MIME type actually matches the real content type. However, one media file can map to multiple MIME types, which are often alternative IANA names of the same type. Public APIs of `mimetype` library only returns one MIME type.

For example, `Content-Type` may be set to `audio/x-wav` and the type detected by `mimetype` shall be `audio/wav`

We internally maintain aliases as shown below, which works for us.

```go
// NOTE: aliases for MIME type detected by
// https://github.com/gabriel-vasile/mimetype/blob/master/supported_mimes.md

// mimeAliases is map in which key is a MIME type detected by
// gabriel-vasile/mimetype and value is list of alternative names
// for same MIME type
var mimeAliases = map[string][]string{
	"audio/wav":       {"audio/wave", "audio/x-wav", "audio/vnd.wave"},
	"audio/midi":      {"audio/mid", "audio/sp-midi", "audio/x-mid", "audio/x-midi"},
	"audio/amr":       {"audio/amr-nb"},
	"audio/mpeg":      {"audio/mp3"},
	"video/x-msvideo": {"video/avi"},
	"video/3gpp":      {"video/3gp", "audio/3gpp"},
	"video/3gpp2":     {"video/3g2", "audio/3gpp2"},
        "video/x-ms-asf":  {"video/asf", "video/x-ms-wmv"},
	"video/webm":      {"audio/webm"},
}
```

Is this something `mimetype` wants to handle/implement ? This could look like:

```go
IsWav(in []byte, mimetype string) bool
```

or via a single API:

```go
Matches(in []byte, mimetype string) bool
```

**Comment by ppai-plivo** [comment]
Another example:
```
The only difference between ASF files and WMV or WMA files are the file extensions
and the MIME types. The MIME type for a WMV file is video/x-ms-wmv, and for WMA
it is audio/x-ms-wma. The MIME type for ASF is video/x-ms-asf. The basic internal
structure of the files is identical.
```

**Comment by gabriel-vasile** [comment]
Hi, I think this is a good addition to the API. This scenario, where you detect the MIME type to check if it is a specific one seems plausible.

Regarding the implementation of this, I think the optional MIME parameters should be dropped when calling `Matches`. 
Ex: provided `in` is a `text/html`, calling `Matches(in, "text/html; charset=UTF-8")` should return true.

As for how the API would look, I lean towards the second option you mentioned.

I will look into this change these days.

**Comment by gabriel-vasile** [comment]
Hi, there is now [Matches](https://github.com/gabriel-vasile/mimetype/blob/514ead325f11482afe909dc3d7adef999fa2dec2/mime.go#L65). I will soon make a release with this, if everything turns out to be good.
