### ISSUE TITLE
Super-charging with other common repos

### ISSUE THREAD

**Issue by DonaldTsang** [gabriel-vasile/mimetype#78]
Other repos that might have useful information in them (if possible turn these into JSON format so that they can be ported into Python and JS)
- https://github.com/floyernick/fleep-py/blob/master/fleep/data.json (193 stars)
- https://github.com/h2non/filetype.py/tree/master/filetype/types (134 stars)
- https://github.com/openpreserve/fido/blob/master/fido/conf/format_extensions.xml (84 stars)
- https://github.com/cdgriffith/puremagic/blob/master/puremagic/magic_data.json (47 stars)
- https://github.com/omriher/Whatype/blob/master/whatype/magics.csv (12 stars)
- https://github.com/schlerp/pyfsig/blob/master/src/pyfsig/file_signatures.py (9 stars)
- https://github.com/7h3rAm/cigma/blob/master/cigma/magicbytes.json (1 star)
- https://github.com/sindresorhus/file-type/blob/master/index.js (1.4k stars)
- https://github.com/h2non/filetype/tree/master/matchers (996 stars)
- https://github.com/richardlehane/siegfried/tree/master/cmd/roy/data/pronom (87 stars)
- https://github.com/rocketRobin/myrmec/blob/master/src/Myrmec/FileTypes.cs (41 stars)
- https://github.com/neilharvey/FileSignatures/tree/master/src/FileSignatures/Formats (34 stars)
- https://github.com/wapmorgan/FileTypeDetector/blob/master/src/Detector.php (15 stars)
- https://github.com/MWSchmid/Rcount/blob/master/source_V2/seqan/seq_io/guess_stream_format.h (12 stars)
- https://github.com/node-modules/buffer-type/blob/master/lib/buffer-type.js (11 stars)
- https://github.com/DBHeise/fileid/blob/master/fileid/magic.h (8 stars)
- https://github.com/0xbrock/FileTypeChecker/blob/master/FileTypeChecker/FileTypeChecker.cs (8 stars)
- https://github.com/SoftCreatR/php-mime-detector/blob/master/src/SoftCreatR/MimeDetector/MimeDetector.php (8 stars)
- https://github.com/dimapaloskin/detect-file-type/blob/master/signatures.json (7 stars)
- https://github.com/liamg/magic/blob/master/types.go (6 stars)
- https://github.com/LarsKoelpin/magic-bytes/blob/master/src/pattern-tree.js (4 stars)
- https://github.com/zhangxiaoyang/FileType/blob/master/FileType.cpp (2 stars)
- https://github.com/stellarbear/MimeMagicSharp/blob/master/samples/magic_json (2 stars)
- https://github.com/ghost1face/FileTypeInterrogator/blob/master/src/FileTypeInterrogator/definitions_flat (2 stars)
- https://github.com/snowinmars/Mimer/blob/master/Mimer/MimeRepository.cs (0 stars)

**Comment by gabriel-vasile** [comment]
If implemented, this would be hard to maintain.
