### ISSUE TITLE
Add support for RPM file format

### ISSUE THREAD

**Issue by gabriel-vasile** [gabriel-vasile/mimetype#84]
1) Specify the MIME type and extension for which to add support
application/x-rpm
2) Share an example file
convert existing test deb file into RPM:
$ cd mimetype/testdata && sudo alien -r deb.deb
3) Optionally, add a reference to the specification of the file format.
[https://github.com/file/file/blob/fd04f3df822e3934c557cf282615a61c04ca2324/magic/Magdir/rpm](https://github.com/file/file/blob/fd04f3df822e3934c557cf282615a61c04ca2324/magic/Magdir/rpm)

**Comment by pippo** [comment]
Can I take that?
