### ISSUE TITLE
mimetype to extension

### ISSUE THREAD

**Issue by codenoid** [gabriel-vasile/mimetype#92]
Go built-in mime package has [ExtensionsByType](https://golang.org/pkg/mime/#ExtensionsByType), but not very complete,

is this package has ExtensionsByType-like function ?

**Comment by gabriel-vasile** [comment]
No, mimetype does not have an ExtensionsByType function.

However there are some packages that extend the built-in list of registered MIME types:
- https://github.com/GitbookIO/mimedb
- https://github.com/jpillora/go-mime
- https://github.com/DronRathore/go-mimes

Maybe one of them provides the function you need.
