### ISSUE TITLE
Add support for cpio file format

### ISSUE THREAD

**Issue by gabriel-vasile** [gabriel-vasile/mimetype#95]
1) Specify the MIME type and extension for which to add support
application/x-cpio, .cpio
2) Share an example file
can be created using cpio executable
3) Optionally, add a reference to the specification of the file format.
https://github.com/apache/tika/blob/86888d9cdf39455bf8bb8dda05e77e790749476b/tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml#L3307

**Comment by crunchbang** [comment]
@gabriel-vasile I would like to take up this enhancement, if it's still open.

**Comment by gabriel-vasile** [comment]
Sure. As far as I know, no one is working on it.
