### ISSUE TITLE
Add support for torrent file format

### ISSUE THREAD

**Issue by gabriel-vasile** [gabriel-vasile/mimetype#96]
1) Specify the MIME type and extension for which to add support
application/x-bittorrent, .torrent
2) Share an example file
use any from the internet, but not a copyrighted one.
3) Optionally, add a reference to the specification of the file format.
https://github.com/apache/tika/blob/86888d9cdf39455bf8bb8dda05e77e790749476b/tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml#L3221

**Comment by ashikjm** [comment]
Hi, I would like to help with this one.

Do you suggest that we validate whole of the bencoded string or just check for 'd8:announce' in the beginning?

**Comment by gabriel-vasile** [comment]
Hi, checking for 'd8:announce' is perfect. We usually try validation of the whole data when there is no signature for a format.

**Comment by ashikjm** [comment]
I have submitted a pull request for the same(#99). Please review.
